SET PATH=D:\keil5\ARM\ARMCLANG\Bin;D:\keil5\ARM\ARMCC\Bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;D:\MAtlab\runtime\win64;D:\MAtlab\bin;C:\Program Files (x86)\STMicroelectronics\STM32 ST-LINK Utility\ST-LINK Utility;C:\Users\asus\AppData\Local\Microsoft\WindowsApps;C:\Users\asus\AppData\Local\Programs\Ollama;D:\pycharm\PyCharm 2024.3.2\bin;;D:\pycharm\PyCharm Community Edition 2024.3.2\bin;;C:\Anaconda;C:\Anaconda\Scripts;C:\Anaconda\Library\bin;D:\VS_code\Microsoft VS Code\bin;C:\Program Files\Graphviz\bin;C:\Program Files\Graphviz\bin;
SET CPU_TYPE=STM32F103CB
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Project5-1
SET CPU_CLOCK=0x007A1200
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\main.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\gpio.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_it.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_msp.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\oled.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_gpio_ex.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_tim.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_tim_ex.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_rcc.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_rcc_ex.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_gpio.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_dma.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_cortex.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_pwr.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_flash.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_flash_ex.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\stm32f1xx_hal_exti.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmCC" --Via "project5-1\system_stm32f1xx.__i"
"D:\keil5\ARM\ARMCC\Bin\ArmLink" --Via "Project5-1\Project5-1.lnp"
